### ISSUE TITLE
Why "OS: Ubuntu 14.04"?

### ISSUE THREAD

**Issue by pvolyntsev** [diogocavilha/vagrant-php-phalcon#1]
Why you wrote "OS: Ubuntu 14.04"? Base box is not specified.

```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.box = "boxname"
```

**Comment by diogocavilha** [comment]
Oh my! Sorry for that. You're right. That's because I'm using ubuntu 14.04 as a base box in a project. 
I'll change the readme file. Thanks for that.
